version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3100:80'  # Exposing frontend on port 3100
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - '4000:4000'  # Exposing backend on port 4000
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase  # Update with your database name
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - ./mongo_data:/data/db  # Persisting MongoDB data

volumes:
  mongo_data:
